import SwiftUI

@MainActor
extension LocalizedStringKey {
    static let connectionTitle = LocalizedStringKey("connection.title")
    static let connectionStatus = LocalizedStringKey("connection.status")
    static let connectionConnected = LocalizedStringKey("connection.status.connected %@")
    static let connectionConnecting = LocalizedStringKey("connection.status.connecting")
    static let connectionScanning = LocalizedStringKey("connection.status.scanning")
    static let connectionDisconnected = LocalizedStringKey("connection.status.disconnected")
    static let connectionConnectingShort = LocalizedStringKey("connection.status.connectingShort")
    static let connectionScanningShort = LocalizedStringKey("connection.status.scanningShort")
    static let connectionDisconnectedShort = LocalizedStringKey("connection.status.disconnectedShort")
    static let connectionShowDetails = LocalizedStringKey("connection.details.show")
    static let connectionHideDetails = LocalizedStringKey("connection.details.hide")
    static let connectionCapabilities = LocalizedStringKey("connection.capabilities")
    static let connectionReconnect = LocalizedStringKey("connection.reconnect.title")
    static let connectionMock = LocalizedStringKey("connection.mock.title")
    static let connectionDiagnostics = LocalizedStringKey("connection.diagnostics.title")
    static let connectionConnect = LocalizedStringKey("connection.connect")
    static let connectionDisconnect = LocalizedStringKey("connection.disconnect")

    static let rgbTitle = LocalizedStringKey("rgb.title")
    static let rgbEffectsTitle = LocalizedStringKey("rgb.effects.title")
    static let rgbColorsTitle = LocalizedStringKey("rgb.colors.title")
    static let rgbPrimary = LocalizedStringKey("rgb.colors.primary")
    static let rgbSecondary = LocalizedStringKey("rgb.colors.secondary")
    static let rgbParametersTitle = LocalizedStringKey("rgb.parameters.title")
    static let rgbDirection = LocalizedStringKey("rgb.direction.label")
    static let rgbSpeed = LocalizedStringKey("rgb.speed.label")
    static let rgbBrightness = LocalizedStringKey("rgb.brightness.label")
    static let rgbZoneTitle = LocalizedStringKey("rgb.zone.title")
    static let rgbZoneEffect = LocalizedStringKey("rgb.zone.effect")
    static let rgbZoneColor = LocalizedStringKey("rgb.zone.color")
    static let rgbApply = LocalizedStringKey("rgb.apply.button")

    static let pollingTitle = LocalizedStringKey("polling.title")
    static let pollingRate = LocalizedStringKey("polling.rate")

    static let knobTitle = LocalizedStringKey("knob.title")
    static let knobBehavior = LocalizedStringKey("knob.behavior")

    static let remapTitle = LocalizedStringKey("remap.title")
    static let remapResetAll = LocalizedStringKey("remap.resetAll")
    static let remapMappings = LocalizedStringKey("remap.mappings")
    static let remapActionStandard = LocalizedStringKey("remap.action.standard")
    static let remapActionMedia = LocalizedStringKey("remap.action.media")
    static let remapActionMouse = LocalizedStringKey("remap.action.mouse")
    static let remapActionMacro = LocalizedStringKey("remap.action.macro")
    static let remapActionDisable = LocalizedStringKey("remap.action.disable")

    static let macroTitle = LocalizedStringKey("macro.title")
    static let macroNew = LocalizedStringKey("macro.new")
    static let macroEmptyTitle = LocalizedStringKey("macro.empty.title")
    static let macroCreateFirst = LocalizedStringKey("macro.createFirst")
    static let macroEditTitle = LocalizedStringKey("macro.edit.title")
    static let macroNamePlaceholder = LocalizedStringKey("macro.namePlaceholder")
    static let macroRecord = LocalizedStringKey("macro.record")
    static let macroStopRecording = LocalizedStringKey("macro.stopRecording")
    static let macroClear = LocalizedStringKey("macro.clear")

    static let profileManagerTitle = LocalizedStringKey("profile.manager.title")
    static let profileNew = LocalizedStringKey("app.menu.newProfile")
    static let profileSaveToKB = LocalizedStringKey("profile.saveToKB")
    static let profileActivate = LocalizedStringKey("profile.activate")
    static let profileDeleteTitle = LocalizedStringKey("profile.delete.title")
    static let profileNamePlaceholder = LocalizedStringKey("profile.namePlaceholder")

    static let generalCancel = LocalizedStringKey("general.cancel")
    static let generalSave = LocalizedStringKey("general.save")
    static let generalDelete = LocalizedStringKey("general.delete")
    static let generalCreate = LocalizedStringKey("general.create")
    static let generalName = LocalizedStringKey("general.name")
    static let generalNoProfile = LocalizedStringKey("general.noActiveProfile")
    static let navActive = LocalizedStringKey("nav.active")

    static let sidebarConnection = LocalizedStringKey("sidebar.connection")
    static let sidebarRGB = LocalizedStringKey("sidebar.rgb")
    static let sidebarRemap = LocalizedStringKey("sidebar.remap")
    static let sidebarMacros = LocalizedStringKey("sidebar.macros")
    static let sidebarKnob = LocalizedStringKey("sidebar.knob")
    static let sidebarPolling = LocalizedStringKey("sidebar.polling")
    static let sidebarProfiles = LocalizedStringKey("sidebar.profiles")
}
